---
- name: Create dev folder
  shell: mkdir -p ~/dev/personal/iterm-themes
  tags:
    - dev-env
- name: Create screenshot folder
  shell: mkdir -p ~/Screenshots
  tags:
    - dev-env
- name: Download tokyo night iterm theme
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/enkia/tokyo-night-vscode-theme/master/tokyo-night.itermcolors
    dest: ~/dev/personal/iterm-themes
  tags:
    - dev-env
- name: Download duskfox iterm theme
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/EdenEast/nightfox.nvim/main/extra/duskfox/nightfox_iterm.itermcolors
    dest: ~/dev/personal/iterm-themes
  tags:
    - dev-env
- name: Download nightfox iterm theme
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/EdenEast/nightfox.nvim/main/extra/nightfox/nightfox_iterm.itermcolors
    dest: ~/dev/personal/iterm-themes
  tags:
    - dev-env
- name: Download and unzip Inconsolata Nerd Font
  ansible.builtin.unarchive:
    src: https://github.com/ryanoasis/nerd-fonts/releases/download/v2.3.3/Inconsolata.zip
    dest: ~/Library/Fonts
    remote_src: true
  tags:
    - dev-env
- name: Download Esc Mapping Script
  ansible.builtin.get_url:
    url: https://gist.githubusercontent.com/liamdawson/8dba17715c452dad996932291193c353/raw/420d97c10526403849d8a5279cb2007840e546cd/com.ldaws.CapslockEsc.plist
    dest: ~/Library/LaunchAgents/com.ldaws.CapslockEsc.plist
  tags:
    - dev-env
- name: Add Esc Script to Launch Control
  ansible.builtin.shell:
    cmd: launchctl load com.ldaws.CapslockEsc.plist
    chdir: ~/Library/LaunchAgents
  tags:
    - dev-env
- name: Add iTerm2 Preferences
  ansible.builtin.shell:
    cmd: stow --target $HOME iterm2
    chdir: ~/dev/personal/dotfiles
  tags:
    - dev-env
