---
- name: Install brew terminal apps
  ansible.builtin.shell:
    cmd: brew install jq ripgrep fzf bat fd exercism tig watchman git tree-sitter
  args:
    executable: /bin/bash
  tags:
    - dev-tools
- name: Install brew cask apps
  ansible.builtin.shell:
    cmd: brew install --cask ngrok rescuetime iterm2 docker anaconda karabiner-elements devtoys insomnia
  args:
    executable: /bin/bash
  tags:
    - dev-tools
