---
- name: Create dev folder
  shell: mkdir -p ~/dev/personal/iterm-themes
  tags:
    - dev-env
- name: Create screenshot folder
  shell: mkdir -p ~/Screenshots
  tags:
    - dev-env
- name: Download tokyo night iterm theme
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/enkia/tokyo-night-vscode-theme/master/tokyo-night.itermcolors
    dest: ~/dev/personal/iterm-themes
  tags:
    - dev-env
- name: Download duskfox iterm theme
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/EdenEast/nightfox.nvim/main/extra/duskfox/nightfox_iterm.itermcolors
    dest: ~/dev/personal/iterm-themes
  tags:
    - dev-env
- name: Download nightfox iterm theme
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/EdenEast/nightfox.nvim/main/extra/nightfox/nightfox_iterm.itermcolors
    dest: ~/dev/personal/iterm-themes
  tags:
    - dev-env
- name: Download and unzip Inconsolata Nerd Font
  ansible.builtin.unarchive:
    src: https://github.com/ryanoasis/nerd-fonts/releases/download/v3.0.2/Inconsolata.zip
    dest: ~/Library/Fonts
    remote_src: true
  tags:
    - dev-env
- name: Add iTerm2 Preferences
  ansible.builtin.shell:
    cmd: stow --target $HOME iterm2
    chdir: ~/dev/personal/dotfiles
  tags:
    - dev-env
