---
- name: Install golang
  ansible.builtin.shell:
    cmd: brew install go
  args:
    executable: /bin/bash
  tags:
    - languages
- name: Install lua
  ansible.builtin.shell:
    cmd: brew install lua luajit luarocks
  args:
    executable: /bin/bash
  tags:
    - languages
- name: Install rust
  ansible.builtin.shell:
    cmd: brew install rustup
  args:
    executable: /bin/bash
  tags:
    - languages
