---
- name: Install fnm
  ansible.builtin.shell:
    cmd: brew install fnm
  args:
    executable: /bin/bash
  tags:
    - node
- name: Install LTS node
  ansible.builtin.shell:
    cmd: fnm install --lts
  args:
    executable: /bin/bash
  tags:
    - node
