---
- name: New System Setup
  hosts: localhost
  become: true
  become_user: blake
  tasks:
    - import_tasks: zsh.yml
    - import_tasks: node.yml
    - import_tasks: languages.yml
    - import_tasks: dotfiles.yml
    - import_tasks: neovim.yml
    - import_tasks: tmux.yml
    - import_tasks: dev-tools.yml
    - import_tasks: dev-env.yml
