---
- name: Install zsh
  ansible.builtin.shell:
    cmd: brew install zsh
  args:
    executable: /bin/bash
  tags:
    - zsh
- name: Install oh-my-zsh
  ansible.builtin.shell:
    cmd: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  tags:
    - zsh
- name: Install zsh-autosuggestions
  ansible.builtin.shell:
    cmd: brew install zsh-autosuggestions
  args:
    executable: /bin/bash
  tags:
    - zsh
- name: Install zsh-autosuggestions
  ansible.builtin.shell:
    cmd: brew install zsh-autosuggestions
  args:
    executable: /bin/bash
  tags:
    - zsh
